/* rygel-gst-connection-manager.c generated by valac, the Vala compiler
 * generated from rygel-gst-connection-manager.vala, do not modify */

/*
 * Copyright (C) 2008 OpenedHand Ltd.
 * Copyright (C) 2009 Nokia Corporation.
 *
 * Author: Jorn Baayen <jorn@openedhand.com>
 *         Zeeshan Ali (Khattak) <zeeshanak@gnome.org>
 *                               <zeeshan.ali@nokia.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 */

#include <glib.h>
#include <glib-object.h>
#include <rygel.h>


#define RYGEL_TYPE_GST_CONNECTION_MANAGER (rygel_gst_connection_manager_get_type ())
#define RYGEL_GST_CONNECTION_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_GST_CONNECTION_MANAGER, RygelGstConnectionManager))
#define RYGEL_GST_CONNECTION_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_GST_CONNECTION_MANAGER, RygelGstConnectionManagerClass))
#define RYGEL_IS_GST_CONNECTION_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_GST_CONNECTION_MANAGER))
#define RYGEL_IS_GST_CONNECTION_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_GST_CONNECTION_MANAGER))
#define RYGEL_GST_CONNECTION_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_GST_CONNECTION_MANAGER, RygelGstConnectionManagerClass))

typedef struct _RygelGstConnectionManager RygelGstConnectionManager;
typedef struct _RygelGstConnectionManagerClass RygelGstConnectionManagerClass;
typedef struct _RygelGstConnectionManagerPrivate RygelGstConnectionManagerPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _RygelGstConnectionManager {
	RygelConnectionManager parent_instance;
	RygelGstConnectionManagerPrivate * priv;
};

struct _RygelGstConnectionManagerClass {
	RygelConnectionManagerClass parent_class;
};


static gpointer rygel_gst_connection_manager_parent_class = NULL;

GType rygel_gst_connection_manager_get_type (void);
enum  {
	RYGEL_GST_CONNECTION_MANAGER_DUMMY_PROPERTY
};
static void rygel_gst_connection_manager_real_constructed (GObject* base);
RygelGstConnectionManager* rygel_gst_connection_manager_new (void);
RygelGstConnectionManager* rygel_gst_connection_manager_construct (GType object_type);



#line 66 "rygel-gst-connection-manager.vala"
static void rygel_gst_connection_manager_real_constructed (GObject* base) {
#line 73 "rygel-gst-connection-manager.c"
	RygelGstConnectionManager * self;
	char* _tmp0_;
	char* _tmp1_;
	char* _tmp2_;
	self = (RygelGstConnectionManager*) base;
#line 67 "rygel-gst-connection-manager.vala"
	G_OBJECT_CLASS (rygel_gst_connection_manager_parent_class)->constructed ((GObject*) RYGEL_CONNECTION_MANAGER (self));
#line 69 "rygel-gst-connection-manager.vala"
	((RygelConnectionManager*) self)->connection_ids = (_tmp0_ = g_strdup ("0"), _g_free0 (((RygelConnectionManager*) self)->connection_ids), _tmp0_);
#line 70 "rygel-gst-connection-manager.vala"
	((RygelConnectionManager*) self)->source_protocol_info = (_tmp1_ = g_strdup (""), _g_free0 (((RygelConnectionManager*) self)->source_protocol_info), _tmp1_);
#line 71 "rygel-gst-connection-manager.vala"
	((RygelConnectionManager*) self)->sink_protocol_info = (_tmp2_ = g_strdup ("http-get:*:audio/mpeg:*," "http-get:*:application/ogg:*," "http-get:*:audio/x-vorbis:*," "http-get:*:audio/x-vorbis+ogg:*," "http-get:*:audio/x-ms-wma:*," "http-get:*:audio/x-ms-asf:*," "http-get:*:audio/x-flac:*," "http-get:*:audio/x-mod:*," "http-get:*:audio/x-wav:*," "http-get:*:audio/x-ac3:*," "http-get:*:audio/x-m4a:*," "http-get:*:video/x-theora:*," "http-get:*:video/x-dirac:*," "http-get:*:video/x-wmv:*," "http-get:*:video/x-wma:*," "http-get:*:video/x-msvideo:*," "http-get:*:video/x-3ivx:*," "http-get:*:video/x-3ivx:*," "http-get:*:video/x-matroska:*," "http-get:*:video/mpeg:*," "http-get:*:video/x-ms-asf:*," "http-get:*:video/x-xvid:*," "http-get:*:video/x-ms-wmv:*," "http-get:*:audio/L16;" "rate=44100;" "channels=2:*," "http-get:*:audio/L16;" "rate=44100;" "channels=1:*"), _g_free0 (((RygelConnectionManager*) self)->sink_protocol_info), _tmp2_);
#line 87 "rygel-gst-connection-manager.c"
}


#line 30 "rygel-gst-connection-manager.vala"
RygelGstConnectionManager* rygel_gst_connection_manager_construct (GType object_type) {
#line 93 "rygel-gst-connection-manager.c"
	RygelGstConnectionManager * self;
#line 30 "rygel-gst-connection-manager.vala"
	self = (RygelGstConnectionManager*) rygel_connection_manager_construct (object_type);
#line 97 "rygel-gst-connection-manager.c"
	return self;
}


#line 30 "rygel-gst-connection-manager.vala"
RygelGstConnectionManager* rygel_gst_connection_manager_new (void) {
#line 30 "rygel-gst-connection-manager.vala"
	return rygel_gst_connection_manager_construct (RYGEL_TYPE_GST_CONNECTION_MANAGER);
#line 106 "rygel-gst-connection-manager.c"
}


static void rygel_gst_connection_manager_class_init (RygelGstConnectionManagerClass * klass) {
	rygel_gst_connection_manager_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->constructed = rygel_gst_connection_manager_real_constructed;
}


static void rygel_gst_connection_manager_instance_init (RygelGstConnectionManager * self) {
}


GType rygel_gst_connection_manager_get_type (void) {
	static GType rygel_gst_connection_manager_type_id = 0;
	if (rygel_gst_connection_manager_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (RygelGstConnectionManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) rygel_gst_connection_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RygelGstConnectionManager), 0, (GInstanceInitFunc) rygel_gst_connection_manager_instance_init, NULL };
		rygel_gst_connection_manager_type_id = g_type_register_static (RYGEL_TYPE_CONNECTION_MANAGER, "RygelGstConnectionManager", &g_define_type_info, 0);
	}
	return rygel_gst_connection_manager_type_id;
}




