/* rygel-content-directory.c generated by valac, the Vala compiler
 * generated from rygel-content-directory.vala, do not modify */

/*
 * Copyright (C) 2008 Zeeshan Ali <zeenix@gmail.com>.
 * Copyright (C) 2007 OpenedHand Ltd.
 *
 * Author: Zeeshan Ali <zeenix@gmail.com>
 *         Jorn Baayen <jorn@openedhand.com>
 *
 * This file is part of Rygel.
 *
 * Rygel is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Rygel is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <libgupnp/gupnp.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <gee.h>
#include <glib/gi18n-lib.h>


#define RYGEL_TYPE_CONTENT_DIRECTORY (rygel_content_directory_get_type ())
#define RYGEL_CONTENT_DIRECTORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_CONTENT_DIRECTORY, RygelContentDirectory))
#define RYGEL_CONTENT_DIRECTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_CONTENT_DIRECTORY, RygelContentDirectoryClass))
#define RYGEL_IS_CONTENT_DIRECTORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_CONTENT_DIRECTORY))
#define RYGEL_IS_CONTENT_DIRECTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_CONTENT_DIRECTORY))
#define RYGEL_CONTENT_DIRECTORY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_CONTENT_DIRECTORY, RygelContentDirectoryClass))

typedef struct _RygelContentDirectory RygelContentDirectory;
typedef struct _RygelContentDirectoryClass RygelContentDirectoryClass;
typedef struct _RygelContentDirectoryPrivate RygelContentDirectoryPrivate;

#define RYGEL_TYPE_TRANSCODE_MANAGER (rygel_transcode_manager_get_type ())
#define RYGEL_TRANSCODE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_TRANSCODE_MANAGER, RygelTranscodeManager))
#define RYGEL_TRANSCODE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_TRANSCODE_MANAGER, RygelTranscodeManagerClass))
#define RYGEL_IS_TRANSCODE_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_TRANSCODE_MANAGER))
#define RYGEL_IS_TRANSCODE_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_TRANSCODE_MANAGER))
#define RYGEL_TRANSCODE_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_TRANSCODE_MANAGER, RygelTranscodeManagerClass))

typedef struct _RygelTranscodeManager RygelTranscodeManager;
typedef struct _RygelTranscodeManagerClass RygelTranscodeManagerClass;

#define RYGEL_TYPE_HTTP_SERVER (rygel_http_server_get_type ())
#define RYGEL_HTTP_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_HTTP_SERVER, RygelHTTPServer))
#define RYGEL_HTTP_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_HTTP_SERVER, RygelHTTPServerClass))
#define RYGEL_IS_HTTP_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_HTTP_SERVER))
#define RYGEL_IS_HTTP_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_HTTP_SERVER))
#define RYGEL_HTTP_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_HTTP_SERVER, RygelHTTPServerClass))

typedef struct _RygelHTTPServer RygelHTTPServer;
typedef struct _RygelHTTPServerClass RygelHTTPServerClass;

#define RYGEL_TYPE_MEDIA_OBJECT (rygel_media_object_get_type ())
#define RYGEL_MEDIA_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_MEDIA_OBJECT, RygelMediaObject))
#define RYGEL_MEDIA_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_MEDIA_OBJECT, RygelMediaObjectClass))
#define RYGEL_IS_MEDIA_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_MEDIA_OBJECT))
#define RYGEL_IS_MEDIA_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_MEDIA_OBJECT))
#define RYGEL_MEDIA_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_MEDIA_OBJECT, RygelMediaObjectClass))

typedef struct _RygelMediaObject RygelMediaObject;
typedef struct _RygelMediaObjectClass RygelMediaObjectClass;

#define RYGEL_TYPE_MEDIA_CONTAINER (rygel_media_container_get_type ())
#define RYGEL_MEDIA_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_MEDIA_CONTAINER, RygelMediaContainer))
#define RYGEL_MEDIA_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_MEDIA_CONTAINER, RygelMediaContainerClass))
#define RYGEL_IS_MEDIA_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_MEDIA_CONTAINER))
#define RYGEL_IS_MEDIA_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_MEDIA_CONTAINER))
#define RYGEL_MEDIA_CONTAINER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_MEDIA_CONTAINER, RygelMediaContainerClass))

typedef struct _RygelMediaContainer RygelMediaContainer;
typedef struct _RygelMediaContainerClass RygelMediaContainerClass;

#define RYGEL_TYPE_IMPORT_RESOURCE (rygel_import_resource_get_type ())
#define RYGEL_IMPORT_RESOURCE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_IMPORT_RESOURCE, RygelImportResource))
#define RYGEL_IMPORT_RESOURCE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_IMPORT_RESOURCE, RygelImportResourceClass))
#define RYGEL_IS_IMPORT_RESOURCE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_IMPORT_RESOURCE))
#define RYGEL_IS_IMPORT_RESOURCE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_IMPORT_RESOURCE))
#define RYGEL_IMPORT_RESOURCE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_IMPORT_RESOURCE, RygelImportResourceClass))

typedef struct _RygelImportResource RygelImportResource;
typedef struct _RygelImportResourceClass RygelImportResourceClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define RYGEL_TYPE_PLUGIN (rygel_plugin_get_type ())
#define RYGEL_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_PLUGIN, RygelPlugin))
#define RYGEL_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_PLUGIN, RygelPluginClass))
#define RYGEL_IS_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_PLUGIN))
#define RYGEL_IS_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_PLUGIN))
#define RYGEL_PLUGIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_PLUGIN, RygelPluginClass))

typedef struct _RygelPlugin RygelPlugin;
typedef struct _RygelPluginClass RygelPluginClass;

#define RYGEL_TYPE_MEDIA_SERVER_PLUGIN (rygel_media_server_plugin_get_type ())
#define RYGEL_MEDIA_SERVER_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_MEDIA_SERVER_PLUGIN, RygelMediaServerPlugin))
#define RYGEL_MEDIA_SERVER_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_MEDIA_SERVER_PLUGIN, RygelMediaServerPluginClass))
#define RYGEL_IS_MEDIA_SERVER_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_MEDIA_SERVER_PLUGIN))
#define RYGEL_IS_MEDIA_SERVER_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_MEDIA_SERVER_PLUGIN))
#define RYGEL_MEDIA_SERVER_PLUGIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_MEDIA_SERVER_PLUGIN, RygelMediaServerPluginClass))

typedef struct _RygelMediaServerPlugin RygelMediaServerPlugin;
typedef struct _RygelMediaServerPluginClass RygelMediaServerPluginClass;
typedef struct _RygelPluginPrivate RygelPluginPrivate;

#define RYGEL_TYPE_RESOURCE_INFO (rygel_resource_info_get_type ())
#define RYGEL_RESOURCE_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_RESOURCE_INFO, RygelResourceInfo))
#define RYGEL_RESOURCE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_RESOURCE_INFO, RygelResourceInfoClass))
#define RYGEL_IS_RESOURCE_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_RESOURCE_INFO))
#define RYGEL_IS_RESOURCE_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_RESOURCE_INFO))
#define RYGEL_RESOURCE_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_RESOURCE_INFO, RygelResourceInfoClass))

typedef struct _RygelResourceInfo RygelResourceInfo;
typedef struct _RygelResourceInfoClass RygelResourceInfoClass;

#define RYGEL_TYPE_ICON_INFO (rygel_icon_info_get_type ())
#define RYGEL_ICON_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_ICON_INFO, RygelIconInfo))
#define RYGEL_ICON_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_ICON_INFO, RygelIconInfoClass))
#define RYGEL_IS_ICON_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_ICON_INFO))
#define RYGEL_IS_ICON_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_ICON_INFO))
#define RYGEL_ICON_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_ICON_INFO, RygelIconInfoClass))

typedef struct _RygelIconInfo RygelIconInfo;
typedef struct _RygelIconInfoClass RygelIconInfoClass;
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define RYGEL_TYPE_STATE_MACHINE (rygel_state_machine_get_type ())
#define RYGEL_STATE_MACHINE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_STATE_MACHINE, RygelStateMachine))
#define RYGEL_IS_STATE_MACHINE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_STATE_MACHINE))
#define RYGEL_STATE_MACHINE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), RYGEL_TYPE_STATE_MACHINE, RygelStateMachineIface))

typedef struct _RygelStateMachine RygelStateMachine;
typedef struct _RygelStateMachineIface RygelStateMachineIface;

#define RYGEL_TYPE_MEDIA_QUERY_ACTION (rygel_media_query_action_get_type ())
#define RYGEL_MEDIA_QUERY_ACTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_MEDIA_QUERY_ACTION, RygelMediaQueryAction))
#define RYGEL_MEDIA_QUERY_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_MEDIA_QUERY_ACTION, RygelMediaQueryActionClass))
#define RYGEL_IS_MEDIA_QUERY_ACTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_MEDIA_QUERY_ACTION))
#define RYGEL_IS_MEDIA_QUERY_ACTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_MEDIA_QUERY_ACTION))
#define RYGEL_MEDIA_QUERY_ACTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_MEDIA_QUERY_ACTION, RygelMediaQueryActionClass))

typedef struct _RygelMediaQueryAction RygelMediaQueryAction;
typedef struct _RygelMediaQueryActionClass RygelMediaQueryActionClass;

#define RYGEL_TYPE_BROWSE (rygel_browse_get_type ())
#define RYGEL_BROWSE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_BROWSE, RygelBrowse))
#define RYGEL_BROWSE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_BROWSE, RygelBrowseClass))
#define RYGEL_IS_BROWSE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_BROWSE))
#define RYGEL_IS_BROWSE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_BROWSE))
#define RYGEL_BROWSE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_BROWSE, RygelBrowseClass))

typedef struct _RygelBrowse RygelBrowse;
typedef struct _RygelBrowseClass RygelBrowseClass;

#define RYGEL_TYPE_SEARCH (rygel_search_get_type ())
#define RYGEL_SEARCH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_SEARCH, RygelSearch))
#define RYGEL_SEARCH_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_SEARCH, RygelSearchClass))
#define RYGEL_IS_SEARCH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_SEARCH))
#define RYGEL_IS_SEARCH_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_SEARCH))
#define RYGEL_SEARCH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_SEARCH, RygelSearchClass))

typedef struct _RygelSearch RygelSearch;
typedef struct _RygelSearchClass RygelSearchClass;

#define RYGEL_TYPE_ITEM_CREATOR (rygel_item_creator_get_type ())
#define RYGEL_ITEM_CREATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_ITEM_CREATOR, RygelItemCreator))
#define RYGEL_ITEM_CREATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_ITEM_CREATOR, RygelItemCreatorClass))
#define RYGEL_IS_ITEM_CREATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_ITEM_CREATOR))
#define RYGEL_IS_ITEM_CREATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_ITEM_CREATOR))
#define RYGEL_ITEM_CREATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_ITEM_CREATOR, RygelItemCreatorClass))

typedef struct _RygelItemCreator RygelItemCreator;
typedef struct _RygelItemCreatorClass RygelItemCreatorClass;
typedef struct _RygelImportResourcePrivate RygelImportResourcePrivate;

#define RYGEL_TYPE_TRANSFER_STATUS (rygel_transfer_status_get_type ())
typedef struct _RygelMediaObjectPrivate RygelMediaObjectPrivate;
typedef struct _RygelMediaContainerPrivate RygelMediaContainerPrivate;

#define RYGEL_TYPE_MEDIA_OBJECTS (rygel_media_objects_get_type ())
#define RYGEL_MEDIA_OBJECTS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_MEDIA_OBJECTS, RygelMediaObjects))
#define RYGEL_MEDIA_OBJECTS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_MEDIA_OBJECTS, RygelMediaObjectsClass))
#define RYGEL_IS_MEDIA_OBJECTS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_MEDIA_OBJECTS))
#define RYGEL_IS_MEDIA_OBJECTS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_MEDIA_OBJECTS))
#define RYGEL_MEDIA_OBJECTS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_MEDIA_OBJECTS, RygelMediaObjectsClass))

typedef struct _RygelMediaObjects RygelMediaObjects;
typedef struct _RygelMediaObjectsClass RygelMediaObjectsClass;

#define RYGEL_TYPE_SEARCH_EXPRESSION (rygel_search_expression_get_type ())
#define RYGEL_SEARCH_EXPRESSION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_SEARCH_EXPRESSION, RygelSearchExpression))
#define RYGEL_SEARCH_EXPRESSION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_SEARCH_EXPRESSION, RygelSearchExpressionClass))
#define RYGEL_IS_SEARCH_EXPRESSION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_SEARCH_EXPRESSION))
#define RYGEL_IS_SEARCH_EXPRESSION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_SEARCH_EXPRESSION))
#define RYGEL_SEARCH_EXPRESSION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_SEARCH_EXPRESSION, RygelSearchExpressionClass))

typedef struct _RygelSearchExpression RygelSearchExpression;
typedef struct _RygelSearchExpressionClass RygelSearchExpressionClass;

#define RYGEL_TYPE_MEDIA_ITEM (rygel_media_item_get_type ())
#define RYGEL_MEDIA_ITEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_MEDIA_ITEM, RygelMediaItem))
#define RYGEL_MEDIA_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_MEDIA_ITEM, RygelMediaItemClass))
#define RYGEL_IS_MEDIA_ITEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_MEDIA_ITEM))
#define RYGEL_IS_MEDIA_ITEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_MEDIA_ITEM))
#define RYGEL_MEDIA_ITEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_MEDIA_ITEM, RygelMediaItemClass))

typedef struct _RygelMediaItem RygelMediaItem;
typedef struct _RygelMediaItemClass RygelMediaItemClass;
typedef struct _Block1Data Block1Data;

typedef enum  {
	RYGEL_CONTENT_DIRECTORY_ERROR_NO_SUCH_OBJECT = 701,
	RYGEL_CONTENT_DIRECTORY_ERROR_BAD_METADATA = 712,
	RYGEL_CONTENT_DIRECTORY_ERROR_RESTRICTED_PARENT = 713,
	RYGEL_CONTENT_DIRECTORY_ERROR_CANT_PROCESS = 720,
	RYGEL_CONTENT_DIRECTORY_ERROR_INVALID_ARGS = 402
} RygelContentDirectoryError;
#define RYGEL_CONTENT_DIRECTORY_ERROR rygel_content_directory_error_quark ()
struct _RygelContentDirectory {
	GUPnPService parent_instance;
	RygelContentDirectoryPrivate * priv;
	char* feature_list;
	RygelHTTPServer* http_server;
	RygelMediaContainer* root_container;
	GCancellable* cancellable;
	guint32 system_update_id;
};

struct _RygelContentDirectoryClass {
	GUPnPServiceClass parent_class;
};

struct _RygelContentDirectoryPrivate {
	GeeArrayList* updated_containers;
	GeeArrayList* active_imports;
	gboolean clear_updated_containers;
	guint update_notify_id;
};

struct _RygelPlugin {
	GUPnPResourceFactory parent_instance;
	RygelPluginPrivate * priv;
	char* name;
	char* title;
	char* description;
	char* desc_path;
	GeeArrayList* resource_infos;
	GeeArrayList* icon_infos;
	GeeArrayList* default_icons;
};

struct _RygelPluginClass {
	GUPnPResourceFactoryClass parent_class;
};

struct _RygelStateMachineIface {
	GTypeInterface parent_iface;
	void (*run) (RygelStateMachine* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*run_finish) (RygelStateMachine* self, GAsyncResult* _res_);
	GCancellable* (*get_cancellable) (RygelStateMachine* self);
	void (*set_cancellable) (RygelStateMachine* self, GCancellable* value);
};

typedef enum  {
	RYGEL_TRANSFER_STATUS_COMPLETED,
	RYGEL_TRANSFER_STATUS_ERROR,
	RYGEL_TRANSFER_STATUS_IN_PROGRESS,
	RYGEL_TRANSFER_STATUS_STOPPED
} RygelTransferStatus;

struct _RygelImportResource {
	GObject parent_instance;
	RygelImportResourcePrivate * priv;
	char* source_uri;
	char* destination_uri;
	guint32 transfer_id;
	RygelTransferStatus status;
	gint64 bytes_copied;
	gint64 bytes_total;
};

struct _RygelImportResourceClass {
	GObjectClass parent_class;
};

struct _RygelMediaObject {
	GObject parent_instance;
	RygelMediaObjectPrivate * priv;
	char* id;
	char* upnp_class;
	guint64 modified;
	GeeArrayList* uris;
	RygelMediaContainer* parent;
};

struct _RygelMediaObjectClass {
	GObjectClass parent_class;
	gint (*compare_by_property) (RygelMediaObject* self, RygelMediaObject* media_object, const char* property);
};

struct _RygelMediaContainer {
	RygelMediaObject parent_instance;
	RygelMediaContainerPrivate * priv;
	gint child_count;
	guint32 update_id;
	GeeArrayList* create_classes;
};

struct _RygelMediaContainerClass {
	RygelMediaObjectClass parent_class;
	void (*get_children) (RygelMediaContainer* self, guint offset, guint max_count, GCancellable* cancellable, GAsyncReadyCallback _callback_, gpointer _user_data_);
	RygelMediaObjects* (*get_children_finish) (RygelMediaContainer* self, GAsyncResult* _res_, GError** error);
	void (*search) (RygelMediaContainer* self, RygelSearchExpression* expression, guint offset, guint max_count, GCancellable* cancellable, GAsyncReadyCallback _callback_, gpointer _user_data_);
	RygelMediaObjects* (*search_finish) (RygelMediaContainer* self, GAsyncResult* _res_, guint* total_matches, GError** error);
	void (*find_object) (RygelMediaContainer* self, const char* id, GCancellable* cancellable, GAsyncReadyCallback _callback_, gpointer _user_data_);
	RygelMediaObject* (*find_object_finish) (RygelMediaContainer* self, GAsyncResult* _res_, GError** error);
	void (*add_item) (RygelMediaContainer* self, RygelMediaItem* item, GCancellable* cancellable, GAsyncReadyCallback _callback_, gpointer _user_data_);
	void (*add_item_finish) (RygelMediaContainer* self, GAsyncResult* _res_, GError** error);
};

struct _Block1Data {
	int _ref_count_;
	RygelContentDirectory * self;
	RygelImportResource* import;
};


static gpointer rygel_content_directory_parent_class = NULL;

GQuark rygel_content_directory_error_quark (void);
GType rygel_content_directory_get_type (void) G_GNUC_CONST;
GType rygel_transcode_manager_get_type (void) G_GNUC_CONST;
GType rygel_http_server_get_type (void) G_GNUC_CONST;
GType rygel_media_object_get_type (void) G_GNUC_CONST;
GType rygel_media_container_get_type (void) G_GNUC_CONST;
GType rygel_import_resource_get_type (void) G_GNUC_CONST;
#define RYGEL_CONTENT_DIRECTORY_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), RYGEL_TYPE_CONTENT_DIRECTORY, RygelContentDirectoryPrivate))
enum  {
	RYGEL_CONTENT_DIRECTORY_DUMMY_PROPERTY
};
#define RYGEL_CONTENT_DIRECTORY_UPNP_ID "urn:upnp-org:serviceId:ContentDirectory"
#define RYGEL_CONTENT_DIRECTORY_UPNP_TYPE "urn:schemas-upnp-org:service:ContentDirectory:2"
#define RYGEL_CONTENT_DIRECTORY_UPNP_TYPE_V1 "urn:schemas-upnp-org:service:ContentDirectory:1"
#define RYGEL_CONTENT_DIRECTORY_DESCRIPTION_PATH "xml/ContentDirectory.xml"
GType rygel_plugin_get_type (void) G_GNUC_CONST;
GType rygel_media_server_plugin_get_type (void) G_GNUC_CONST;
RygelMediaContainer* rygel_media_server_plugin_get_root_container (RygelMediaServerPlugin* self, RygelContentDirectory* content_dir);
gpointer rygel_resource_info_ref (gpointer instance);
void rygel_resource_info_unref (gpointer instance);
GParamSpec* rygel_param_spec_resource_info (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void rygel_value_set_resource_info (GValue* value, gpointer v_object);
void rygel_value_take_resource_info (GValue* value, gpointer v_object);
gpointer rygel_value_get_resource_info (const GValue* value);
GType rygel_resource_info_get_type (void) G_GNUC_CONST;
gpointer rygel_icon_info_ref (gpointer instance);
void rygel_icon_info_unref (gpointer instance);
GParamSpec* rygel_param_spec_icon_info (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void rygel_value_set_icon_info (GValue* value, gpointer v_object);
void rygel_value_take_icon_info (GValue* value, gpointer v_object);
gpointer rygel_value_get_icon_info (const GValue* value);
GType rygel_icon_info_get_type (void) G_GNUC_CONST;
RygelHTTPServer* rygel_http_server_new (RygelContentDirectory* content_dir, const char* name, GError** error);
RygelHTTPServer* rygel_http_server_construct (GType object_type, RygelContentDirectory* content_dir, const char* name, GError** error);
static void rygel_content_directory_on_container_updated (RygelContentDirectory* self, RygelMediaContainer* root_container, RygelMediaContainer* updated_container);
static void _rygel_content_directory_on_container_updated_rygel_media_container_container_updated (RygelMediaContainer* _sender, RygelMediaContainer* container, gpointer self);
static void rygel_content_directory_browse_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action);
static void _rygel_content_directory_browse_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self);
static void rygel_content_directory_search_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action);
static void _rygel_content_directory_search_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self);
static void rygel_content_directory_create_object_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action);
static void _rygel_content_directory_create_object_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self);
static void rygel_content_directory_import_resource_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action);
static void _rygel_content_directory_import_resource_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self);
static void rygel_content_directory_get_transfer_progress_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action);
static void _rygel_content_directory_get_transfer_progress_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self);
static void rygel_content_directory_stop_transfer_resource_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action);
static void _rygel_content_directory_stop_transfer_resource_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self);
static void rygel_content_directory_query_transfer_ids (RygelContentDirectory* self, GUPnPService* content_dir, const char* variable, GValue* value);
static void _rygel_content_directory_query_transfer_ids_gupnp_service_query_variable (GUPnPService* _sender, const char* variable, GValue* value, gpointer self);
static void rygel_content_directory_get_system_update_id_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action);
static void _rygel_content_directory_get_system_update_id_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self);
static void rygel_content_directory_query_system_update_id (RygelContentDirectory* self, GUPnPService* content_dir, const char* variable, GValue* value);
static void _rygel_content_directory_query_system_update_id_gupnp_service_query_variable (GUPnPService* _sender, const char* variable, GValue* value, gpointer self);
static void rygel_content_directory_query_container_update_ids (RygelContentDirectory* self, GUPnPService* content_dir, const char* variable, GValue* value);
static void _rygel_content_directory_query_container_update_ids_gupnp_service_query_variable (GUPnPService* _sender, const char* variable, GValue* value, gpointer self);
static void rygel_content_directory_get_search_capabilities_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action);
static void _rygel_content_directory_get_search_capabilities_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self);
static void rygel_content_directory_query_search_capabilities (RygelContentDirectory* self, GUPnPService* content_dir, const char* variable, GValue* value);
static void _rygel_content_directory_query_search_capabilities_gupnp_service_query_variable (GUPnPService* _sender, const char* variable, GValue* value, gpointer self);
static void rygel_content_directory_get_sort_capabilities_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action);
static void _rygel_content_directory_get_sort_capabilities_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self);
static void rygel_content_directory_query_sort_capabilities (RygelContentDirectory* self, GUPnPService* content_dir, const char* variable, GValue* value);
static void _rygel_content_directory_query_sort_capabilities_gupnp_service_query_variable (GUPnPService* _sender, const char* variable, GValue* value, gpointer self);
static void rygel_content_directory_get_feature_list_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action);
static void _rygel_content_directory_get_feature_list_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self);
static void rygel_content_directory_query_feature_list (RygelContentDirectory* self, GUPnPService* content_dir, const char* variable, GValue* value);
static void _rygel_content_directory_query_feature_list_gupnp_service_query_variable (GUPnPService* _sender, const char* variable, GValue* value, gpointer self);
GType rygel_state_machine_get_type (void) G_GNUC_CONST;
void rygel_state_machine_run (RygelStateMachine* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
void rygel_state_machine_run_finish (RygelStateMachine* self, GAsyncResult* _res_);
static void rygel_content_directory_real_constructed (GObject* base);
RygelBrowse* rygel_browse_new (RygelContentDirectory* content_dir, GUPnPServiceAction* action);
RygelBrowse* rygel_browse_construct (GType object_type, RygelContentDirectory* content_dir, GUPnPServiceAction* action);
GType rygel_media_query_action_get_type (void) G_GNUC_CONST;
GType rygel_browse_get_type (void) G_GNUC_CONST;
RygelSearch* rygel_search_new (RygelContentDirectory* content_dir, GUPnPServiceAction* action);
RygelSearch* rygel_search_construct (GType object_type, RygelContentDirectory* content_dir, GUPnPServiceAction* action);
GType rygel_search_get_type (void) G_GNUC_CONST;
RygelItemCreator* rygel_item_creator_new (RygelContentDirectory* content_dir, GUPnPServiceAction* action);
RygelItemCreator* rygel_item_creator_construct (GType object_type, RygelContentDirectory* content_dir, GUPnPServiceAction* action);
GType rygel_item_creator_get_type (void) G_GNUC_CONST;
RygelImportResource* rygel_import_resource_new (RygelContentDirectory* content_dir, GUPnPServiceAction* action);
RygelImportResource* rygel_import_resource_construct (GType object_type, RygelContentDirectory* content_dir, GUPnPServiceAction* action);
static void rygel_content_directory_on_import_completed (RygelContentDirectory* self, RygelStateMachine* machine);
static void _rygel_content_directory_on_import_completed_rygel_state_machine_completed (RygelStateMachine* _sender, gpointer self);
static char* rygel_content_directory_create_transfer_ids (RygelContentDirectory* self);
static RygelImportResource* rygel_content_directory_find_import_for_action (RygelContentDirectory* self, GUPnPServiceAction* action);
const char* rygel_import_resource_get_status_as_string (RygelImportResource* self);
GType rygel_transfer_status_get_type (void) G_GNUC_CONST;
GCancellable* rygel_state_machine_get_cancellable (RygelStateMachine* self);
static char* rygel_content_directory_create_container_update_ids (RygelContentDirectory* self);
#define RYGEL_RELATIONAL_EXPRESSION_CAPS "@id,@parentID,@refID,upnp:class," "dc:title,dc:creator,upnp:createClass," "res,res@protocolInfo"
#define RYGEL_MEDIA_OBJECTS_SORT_CAPS "@id,@parentID,dc:title,upnp:class," "dc:artist,dc:author,upnp:album,dc:date"
GType rygel_media_objects_get_type (void) G_GNUC_CONST;
gpointer rygel_search_expression_ref (gpointer instance);
void rygel_search_expression_unref (gpointer instance);
GParamSpec* rygel_param_spec_search_expression (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void rygel_value_set_search_expression (GValue* value, gpointer v_object);
void rygel_value_take_search_expression (GValue* value, gpointer v_object);
gpointer rygel_value_get_search_expression (const GValue* value);
GType rygel_search_expression_get_type (void) G_GNUC_CONST;
GType rygel_media_item_get_type (void) G_GNUC_CONST;
static gboolean rygel_content_directory_update_notify (RygelContentDirectory* self);
static gboolean _rygel_content_directory_update_notify_gsource_func (gpointer self);
static gboolean _lambda8_ (Block1Data* _data1_);
static gboolean __lambda8__gsource_func (gpointer self);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (Block1Data* _data1_);
RygelContentDirectory* rygel_content_directory_new (void);
RygelContentDirectory* rygel_content_directory_construct (GType object_type);
static void rygel_content_directory_finalize (GObject* obj);
static int _vala_strcmp0 (const char * str1, const char * str2);



GQuark rygel_content_directory_error_quark (void) {
	return g_quark_from_static_string ("rygel_content_directory_error-quark");
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


#line 330 "rygel-content-directory.vala"
static void _rygel_content_directory_on_container_updated_rygel_media_container_container_updated (RygelMediaContainer* _sender, RygelMediaContainer* container, gpointer self) {
#line 475 "rygel-content-directory.c"
	rygel_content_directory_on_container_updated (self, _sender, container);
}


#line 142 "rygel-content-directory.vala"
static void _rygel_content_directory_browse_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self) {
#line 482 "rygel-content-directory.c"
	rygel_content_directory_browse_cb (self, _sender, action);
}


#line 150 "rygel-content-directory.vala"
static void _rygel_content_directory_search_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self) {
#line 489 "rygel-content-directory.c"
	rygel_content_directory_search_cb (self, _sender, action);
}


#line 158 "rygel-content-directory.vala"
static void _rygel_content_directory_create_object_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self) {
#line 496 "rygel-content-directory.c"
	rygel_content_directory_create_object_cb (self, _sender, action);
}


#line 166 "rygel-content-directory.vala"
static void _rygel_content_directory_import_resource_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self) {
#line 503 "rygel-content-directory.c"
	rygel_content_directory_import_resource_cb (self, _sender, action);
}


#line 189 "rygel-content-directory.vala"
static void _rygel_content_directory_get_transfer_progress_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self) {
#line 510 "rygel-content-directory.c"
	rygel_content_directory_get_transfer_progress_cb (self, _sender, action);
}


#line 210 "rygel-content-directory.vala"
static void _rygel_content_directory_stop_transfer_resource_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self) {
#line 517 "rygel-content-directory.c"
	rygel_content_directory_stop_transfer_resource_cb (self, _sender, action);
}


#line 181 "rygel-content-directory.vala"
static void _rygel_content_directory_query_transfer_ids_gupnp_service_query_variable (GUPnPService* _sender, const char* variable, GValue* value, gpointer self) {
#line 524 "rygel-content-directory.c"
	rygel_content_directory_query_transfer_ids (self, _sender, variable, value);
}


#line 223 "rygel-content-directory.vala"
static void _rygel_content_directory_get_system_update_id_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self) {
#line 531 "rygel-content-directory.c"
	rygel_content_directory_get_system_update_id_cb (self, _sender, action);
}


#line 232 "rygel-content-directory.vala"
static void _rygel_content_directory_query_system_update_id_gupnp_service_query_variable (GUPnPService* _sender, const char* variable, GValue* value, gpointer self) {
#line 538 "rygel-content-directory.c"
	rygel_content_directory_query_system_update_id (self, _sender, variable, value);
}


#line 241 "rygel-content-directory.vala"
static void _rygel_content_directory_query_container_update_ids_gupnp_service_query_variable (GUPnPService* _sender, const char* variable, GValue* value, gpointer self) {
#line 545 "rygel-content-directory.c"
	rygel_content_directory_query_container_update_ids (self, _sender, variable, value);
}


#line 252 "rygel-content-directory.vala"
static void _rygel_content_directory_get_search_capabilities_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self) {
#line 552 "rygel-content-directory.c"
	rygel_content_directory_get_search_capabilities_cb (self, _sender, action);
}


#line 261 "rygel-content-directory.vala"
static void _rygel_content_directory_query_search_capabilities_gupnp_service_query_variable (GUPnPService* _sender, const char* variable, GValue* value, gpointer self) {
#line 559 "rygel-content-directory.c"
	rygel_content_directory_query_search_capabilities (self, _sender, variable, value);
}


#line 270 "rygel-content-directory.vala"
static void _rygel_content_directory_get_sort_capabilities_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self) {
#line 566 "rygel-content-directory.c"
	rygel_content_directory_get_sort_capabilities_cb (self, _sender, action);
}


#line 279 "rygel-content-directory.vala"
static void _rygel_content_directory_query_sort_capabilities_gupnp_service_query_variable (GUPnPService* _sender, const char* variable, GValue* value, gpointer self) {
#line 573 "rygel-content-directory.c"
	rygel_content_directory_query_sort_capabilities (self, _sender, variable, value);
}


#line 288 "rygel-content-directory.vala"
static void _rygel_content_directory_get_feature_list_cb_gupnp_service_action_invoked (GUPnPService* _sender, GUPnPServiceAction* action, gpointer self) {
#line 580 "rygel-content-directory.c"
	rygel_content_directory_get_feature_list_cb (self, _sender, action);
}


#line 297 "rygel-content-directory.vala"
static void _rygel_content_directory_query_feature_list_gupnp_service_query_variable (GUPnPService* _sender, const char* variable, GValue* value, gpointer self) {
#line 587 "rygel-content-directory.c"
	rygel_content_directory_query_feature_list (self, _sender, variable, value);
}


#line 68 "rygel-content-directory.vala"
static void rygel_content_directory_real_constructed (GObject* base) {
#line 594 "rygel-content-directory.c"
	RygelContentDirectory * self;
	GError * _inner_error_;
	GCancellable* _tmp0_;
	GUPnPRootDevice* _tmp2_;
	GUPnPRootDevice* _tmp1_ = NULL;
	GUPnPResourceFactory* _tmp3_;
	RygelMediaServerPlugin* _tmp4_;
	RygelMediaServerPlugin* plugin;
	RygelMediaContainer* _tmp5_;
	GeeArrayList* _tmp8_;
	GeeArrayList* _tmp9_;
	char* _tmp10_;
	self = (RygelContentDirectory*) base;
	_inner_error_ = NULL;
#line 69 "rygel-content-directory.vala"
	self->cancellable = (_tmp0_ = g_cancellable_new (), _g_object_unref0 (self->cancellable), _tmp0_);
#line 71 "rygel-content-directory.vala"
	plugin = (_tmp4_ = _g_object_ref0 ((_tmp3_ = gupnp_device_info_get_resource_factory ((GUPnPDeviceInfo*) (_tmp2_ = (g_object_get ((GUPnPService*) self, "root-device", &_tmp1_, NULL), _tmp1_))), RYGEL_IS_MEDIA_SERVER_PLUGIN (_tmp3_) ? ((RygelMediaServerPlugin*) _tmp3_) : NULL)), _g_object_unref0 (_tmp2_), _tmp4_);
#line 73 "rygel-content-directory.vala"
	self->root_container = (_tmp5_ = rygel_media_server_plugin_get_root_container (plugin, self), _g_object_unref0 (self->root_container), _tmp5_);
#line 615 "rygel-content-directory.c"
	{
		RygelHTTPServer* _tmp6_;
		RygelHTTPServer* _tmp7_;
#line 76 "rygel-content-directory.vala"
		_tmp6_ = rygel_http_server_new (self, ((RygelPlugin*) plugin)->name, &_inner_error_);
#line 621 "rygel-content-directory.c"
		if (_inner_error_ != NULL) {
			goto __catch25_g_error;
		}
#line 76 "rygel-content-directory.vala"
		self->http_server = (_tmp7_ = _tmp6_, _g_object_unref0 (self->http_server), _tmp7_);
#line 627 "rygel-content-directory.c"
	}
	goto __finally25;
	__catch25_g_error:
	{
		GError * err;
		err = _inner_error_;
		_inner_error_ = NULL;
		{
#line 78 "rygel-content-directory.vala"
			g_critical (_ ("Failed to create HTTP server for %s: %s"), g_type_name (G_TYPE_FROM_INSTANCE ((GObject*) self)), err->message);
#line 638 "rygel-content-directory.c"
			_g_error_free0 (err);
			_g_object_unref0 (plugin);
#line 81 "rygel-content-directory.vala"
			return;
#line 643 "rygel-content-directory.c"
		}
	}
	__finally25:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (plugin);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
#line 84 "rygel-content-directory.vala"
	self->priv->updated_containers = (_tmp8_ = gee_array_list_new (RYGEL_TYPE_MEDIA_CONTAINER, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL), _g_object_unref0 (self->priv->updated_containers), _tmp8_);
#line 85 "rygel-content-directory.vala"
	self->priv->active_imports = (_tmp9_ = gee_array_list_new (RYGEL_TYPE_IMPORT_RESOURCE, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL), _g_object_unref0 (self->priv->active_imports), _tmp9_);
#line 87 "rygel-content-directory.vala"
	g_signal_connect_object (self->root_container, "container-updated", (GCallback) _rygel_content_directory_on_container_updated_rygel_media_container_container_updated, self, 0);
#line 89 "rygel-content-directory.vala"
	self->feature_list = (_tmp10_ = g_strdup ("<?xml version=\"1.0\" encoding=\"UTF-8\"?>" "<Features xmlns=\"urn:schemas-upnp-org:av:avs\" " "xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" " "xsi:schemaLocation=\"urn:schemas-upnp-org:av:avs" "http://www.upnp.org/schemas/av/avs-v1-20060531.xsd\">" "</Features>"), _g_free0 (self->feature_list), _tmp10_);
#line 97 "rygel-content-directory.vala"
	g_signal_connect_object ((GUPnPService*) self, "action-invoked::Browse", (GCallback) _rygel_content_directory_browse_cb_gupnp_service_action_invoked, self, 0);
#line 98 "rygel-content-directory.vala"
	g_signal_connect_object ((GUPnPService*) self, "action-invoked::Search", (GCallback) _rygel_content_directory_search_cb_gupnp_service_action_invoked, self, 0);
#line 99 "rygel-content-directory.vala"
	g_signal_connect_object ((GUPnPService*) self, "action-invoked::CreateObject", (GCallback) _rygel_content_directory_create_object_cb_gupnp_service_action_invoked, self, 0);
#line 100 "rygel-content-directory.vala"
	g_signal_connect_object ((GUPnPService*) self, "action-invoked::ImportResource", (GCallback) _rygel_content_directory_import_resource_cb_gupnp_service_action_invoked, self, 0);
#line 101 "rygel-content-directory.vala"
	g_signal_connect_object ((GUPnPService*) self, "action-invoked::GetTransferProgress", (GCallback) _rygel_content_directory_get_transfer_progress_cb_gupnp_service_action_invoked, self, 0);
#line 103 "rygel-content-directory.vala"
	g_signal_connect_object ((GUPnPService*) self, "action-invoked::StopTransferResource", (GCallback) _rygel_content_directory_stop_transfer_resource_cb_gupnp_service_action_invoked, self, 0);
#line 106 "rygel-content-directory.vala"
	g_signal_connect_object ((GUPnPService*) self, "query-variable::TransferIDs", (GCallback) _rygel_content_directory_query_transfer_ids_gupnp_service_query_variable, self, 0);
#line 109 "rygel-content-directory.vala"
	g_signal_connect_object ((GUPnPService*) self, "action-invoked::GetSystemUpdateID", (GCallback) _rygel_content_directory_get_system_update_id_cb_gupnp_service_action_invoked, self, 0);
#line 111 "rygel-content-directory.vala"
	g_signal_connect_object ((GUPnPService*) self, "query-variable::SystemUpdateID", (GCallback) _rygel_content_directory_query_system_update_id_gupnp_service_query_variable, self, 0);
#line 113 "rygel-content-directory.vala"
	g_signal_connect_object ((GUPnPService*) self, "query-variable::ContainerUpdateIDs", (GCallback) _rygel_content_directory_query_container_update_ids_gupnp_service_query_variable, self, 0);
#line 117 "rygel-content-directory.vala"
	g_signal_connect_object ((GUPnPService*) self, "action-invoked::GetSearchCapabilities", (GCallback) _rygel_content_directory_get_search_capabilities_cb_gupnp_service_action_invoked, self, 0);
#line 119 "rygel-content-directory.vala"
	g_signal_connect_object ((GUPnPService*) self, "query-variable::SearchCapabilities", (GCallback) _rygel_content_directory_query_search_capabilities_gupnp_service_query_variable, self, 0);
#line 123 "rygel-content-directory.vala"
	g_signal_connect_object ((GUPnPService*) self, "action-invoked::GetSortCapabilities", (GCallback) _rygel_content_directory_get_sort_capabilities_cb_gupnp_service_action_invoked, self, 0);
#line 125 "rygel-content-directory.vala"
	g_signal_connect_object ((GUPnPService*) self, "query-variable::SortCapabilities", (GCallback) _rygel_content_directory_query_sort_capabilities_gupnp_service_query_variable, self, 0);
#line 129 "rygel-content-directory.vala"
	g_signal_connect_object ((GUPnPService*) self, "action-invoked::GetFeatureList", (GCallback) _rygel_content_directory_get_feature_list_cb_gupnp_service_action_invoked, self, 0);
#line 131 "rygel-content-directory.vala"
	g_signal_connect_object ((GUPnPService*) self, "query-variable::FeatureList", (GCallback) _rygel_content_directory_query_feature_list_gupnp_service_query_variable, self, 0);
#line 133 "rygel-content-directory.vala"
	rygel_state_machine_run ((RygelStateMachine*) self->http_server, NULL, NULL);
#line 695 "rygel-content-directory.c"
	_g_object_unref0 (plugin);
}


#line 142 "rygel-content-directory.vala"
static void rygel_content_directory_browse_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action) {
#line 702 "rygel-content-directory.c"
	RygelBrowse* browse;
#line 142 "rygel-content-directory.vala"
	g_return_if_fail (self != NULL);
#line 142 "rygel-content-directory.vala"
	g_return_if_fail (content_dir != NULL);
#line 142 "rygel-content-directory.vala"
	g_return_if_fail (action != NULL);
#line 144 "rygel-content-directory.vala"
	browse = rygel_browse_new (self, action);
#line 146 "rygel-content-directory.vala"
	rygel_state_machine_run ((RygelStateMachine*) browse, NULL, NULL);
#line 714 "rygel-content-directory.c"
	_g_object_unref0 (browse);
}


#line 150 "rygel-content-directory.vala"
static void rygel_content_directory_search_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action) {
#line 721 "rygel-content-directory.c"
	RygelSearch* search;
#line 150 "rygel-content-directory.vala"
	g_return_if_fail (self != NULL);
#line 150 "rygel-content-directory.vala"
	g_return_if_fail (content_dir != NULL);
#line 150 "rygel-content-directory.vala"
	g_return_if_fail (action != NULL);
#line 152 "rygel-content-directory.vala"
	search = rygel_search_new (self, action);
#line 154 "rygel-content-directory.vala"
	rygel_state_machine_run ((RygelStateMachine*) search, NULL, NULL);
#line 733 "rygel-content-directory.c"
	_g_object_unref0 (search);
}


#line 158 "rygel-content-directory.vala"
static void rygel_content_directory_create_object_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action) {
#line 740 "rygel-content-directory.c"
	RygelItemCreator* creator;
#line 158 "rygel-content-directory.vala"
	g_return_if_fail (self != NULL);
#line 158 "rygel-content-directory.vala"
	g_return_if_fail (content_dir != NULL);
#line 158 "rygel-content-directory.vala"
	g_return_if_fail (action != NULL);
#line 160 "rygel-content-directory.vala"
	creator = rygel_item_creator_new (self, action);
#line 162 "rygel-content-directory.vala"
	rygel_state_machine_run ((RygelStateMachine*) creator, NULL, NULL);
#line 752 "rygel-content-directory.c"
	_g_object_unref0 (creator);
}


#line 376 "rygel-content-directory.vala"
static void _rygel_content_directory_on_import_completed_rygel_state_machine_completed (RygelStateMachine* _sender, gpointer self) {
#line 759 "rygel-content-directory.c"
	rygel_content_directory_on_import_completed (self, _sender);
}


#line 166 "rygel-content-directory.vala"
static void rygel_content_directory_import_resource_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action) {
#line 766 "rygel-content-directory.c"
	RygelImportResource* import;
	char* _tmp0_;
#line 166 "rygel-content-directory.vala"
	g_return_if_fail (self != NULL);
#line 166 "rygel-content-directory.vala"
	g_return_if_fail (content_dir != NULL);
#line 166 "rygel-content-directory.vala"
	g_return_if_fail (action != NULL);
#line 168 "rygel-content-directory.vala"
	import = rygel_import_resource_new (self, action);
#line 170 "rygel-content-directory.vala"
	g_signal_connect_object ((RygelStateMachine*) import, "completed", (GCallback) _rygel_content_directory_on_import_completed_rygel_state_machine_completed, self, 0);
#line 171 "rygel-content-directory.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) self->priv->active_imports, import);
#line 173 "rygel-content-directory.vala"
	rygel_state_machine_run ((RygelStateMachine*) import, NULL, NULL);
#line 175 "rygel-content-directory.vala"
	gupnp_service_notify ((GUPnPService*) self, "TransferIDs", G_TYPE_STRING, _tmp0_ = rygel_content_directory_create_transfer_ids (self), NULL);
#line 785 "rygel-content-directory.c"
	_g_free0 (_tmp0_);
	_g_object_unref0 (import);
}


#line 181 "rygel-content-directory.vala"
static void rygel_content_directory_query_transfer_ids (RygelContentDirectory* self, GUPnPService* content_dir, const char* variable, GValue* value) {
#line 793 "rygel-content-directory.c"
	char* _tmp0_;
#line 181 "rygel-content-directory.vala"
	g_return_if_fail (self != NULL);
#line 181 "rygel-content-directory.vala"
	g_return_if_fail (content_dir != NULL);
#line 181 "rygel-content-directory.vala"
	g_return_if_fail (variable != NULL);
#line 184 "rygel-content-directory.vala"
	g_value_init (value, G_TYPE_STRING);
#line 185 "rygel-content-directory.vala"
	g_value_set_string (value, _tmp0_ = rygel_content_directory_create_transfer_ids (self));
#line 805 "rygel-content-directory.c"
	_g_free0 (_tmp0_);
}


#line 189 "rygel-content-directory.vala"
static void rygel_content_directory_get_transfer_progress_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action) {
#line 812 "rygel-content-directory.c"
	RygelImportResource* import;
#line 189 "rygel-content-directory.vala"
	g_return_if_fail (self != NULL);
#line 189 "rygel-content-directory.vala"
	g_return_if_fail (content_dir != NULL);
#line 189 "rygel-content-directory.vala"
	g_return_if_fail (action != NULL);
#line 191 "rygel-content-directory.vala"
	import = rygel_content_directory_find_import_for_action (self, action);
#line 192 "rygel-content-directory.vala"
	if (import != NULL) {
#line 193 "rygel-content-directory.vala"
		gupnp_service_action_set (action, "TransferStatus", G_TYPE_STRING, rygel_import_resource_get_status_as_string (import), "TransferLength", G_TYPE_INT64, import->bytes_copied, "TransferTotal", G_TYPE_INT64, import->bytes_total, NULL);
#line 203 "rygel-content-directory.vala"
		gupnp_service_action_return (action);
#line 828 "rygel-content-directory.c"
	} else {
#line 205 "rygel-content-directory.vala"
		gupnp_service_action_return_error (action, (guint) 717, _ ("No such file transfer"));
#line 832 "rygel-content-directory.c"
	}
	_g_object_unref0 (import);
}


#line 210 "rygel-content-directory.vala"
static void rygel_content_directory_stop_transfer_resource_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action) {
#line 840 "rygel-content-directory.c"
	RygelImportResource* import;
#line 210 "rygel-content-directory.vala"
	g_return_if_fail (self != NULL);
#line 210 "rygel-content-directory.vala"
	g_return_if_fail (content_dir != NULL);
#line 210 "rygel-content-directory.vala"
	g_return_if_fail (action != NULL);
#line 212 "rygel-content-directory.vala"
	import = rygel_content_directory_find_import_for_action (self, action);
#line 213 "rygel-content-directory.vala"
	if (import != NULL) {
#line 214 "rygel-content-directory.vala"
		g_cancellable_cancel (rygel_state_machine_get_cancellable ((RygelStateMachine*) import));
#line 216 "rygel-content-directory.vala"
		gupnp_service_action_return (action);
#line 856 "rygel-content-directory.c"
	} else {
#line 218 "rygel-content-directory.vala"
		gupnp_service_action_return_error (action, (guint) 717, _ ("No such file transfer"));
#line 860 "rygel-content-directory.c"
	}
	_g_object_unref0 (import);
}


#line 223 "rygel-content-directory.vala"
static void rygel_content_directory_get_system_update_id_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action) {
#line 223 "rygel-content-directory.vala"
	g_return_if_fail (self != NULL);
#line 223 "rygel-content-directory.vala"
	g_return_if_fail (content_dir != NULL);
#line 223 "rygel-content-directory.vala"
	g_return_if_fail (action != NULL);
#line 226 "rygel-content-directory.vala"
	gupnp_service_action_set (action, "Id", G_TYPE_UINT, self->system_update_id, NULL);
#line 228 "rygel-content-directory.vala"
	gupnp_service_action_return (action);
#line 878 "rygel-content-directory.c"
}


#line 232 "rygel-content-directory.vala"
static void rygel_content_directory_query_system_update_id (RygelContentDirectory* self, GUPnPService* content_dir, const char* variable, GValue* value) {
#line 232 "rygel-content-directory.vala"
	g_return_if_fail (self != NULL);
#line 232 "rygel-content-directory.vala"
	g_return_if_fail (content_dir != NULL);
#line 232 "rygel-content-directory.vala"
	g_return_if_fail (variable != NULL);
#line 236 "rygel-content-directory.vala"
	g_value_init (value, G_TYPE_UINT);
#line 237 "rygel-content-directory.vala"
	g_value_set_uint (value, (guint) self->system_update_id);
#line 894 "rygel-content-directory.c"
}


#line 241 "rygel-content-directory.vala"
static void rygel_content_directory_query_container_update_ids (RygelContentDirectory* self, GUPnPService* content_dir, const char* variable, GValue* value) {
#line 900 "rygel-content-directory.c"
	char* update_ids;
#line 241 "rygel-content-directory.vala"
	g_return_if_fail (self != NULL);
#line 241 "rygel-content-directory.vala"
	g_return_if_fail (content_dir != NULL);
#line 241 "rygel-content-directory.vala"
	g_return_if_fail (variable != NULL);
#line 244 "rygel-content-directory.vala"
	update_ids = rygel_content_directory_create_container_update_ids (self);
#line 247 "rygel-content-directory.vala"
	g_value_init (value, G_TYPE_STRING);
#line 248 "rygel-content-directory.vala"
	g_value_set_string (value, update_ids);
#line 914 "rygel-content-directory.c"
	_g_free0 (update_ids);
}


#line 252 "rygel-content-directory.vala"
static void rygel_content_directory_get_search_capabilities_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action) {
#line 252 "rygel-content-directory.vala"
	g_return_if_fail (self != NULL);
#line 252 "rygel-content-directory.vala"
	g_return_if_fail (content_dir != NULL);
#line 252 "rygel-content-directory.vala"
	g_return_if_fail (action != NULL);
#line 255 "rygel-content-directory.vala"
	gupnp_service_action_set (action, "SearchCaps", G_TYPE_STRING, RYGEL_RELATIONAL_EXPRESSION_CAPS, NULL);
#line 257 "rygel-content-directory.vala"
	gupnp_service_action_return (action);
#line 931 "rygel-content-directory.c"
}


#line 261 "rygel-content-directory.vala"
static void rygel_content_directory_query_search_capabilities (RygelContentDirectory* self, GUPnPService* content_dir, const char* variable, GValue* value) {
#line 261 "rygel-content-directory.vala"
	g_return_if_fail (self != NULL);
#line 261 "rygel-content-directory.vala"
	g_return_if_fail (content_dir != NULL);
#line 261 "rygel-content-directory.vala"
	g_return_if_fail (variable != NULL);
#line 265 "rygel-content-directory.vala"
	g_value_init (value, G_TYPE_STRING);
#line 266 "rygel-content-directory.vala"
	g_value_set_string (value, RYGEL_RELATIONAL_EXPRESSION_CAPS);
#line 947 "rygel-content-directory.c"
}


#line 270 "rygel-content-directory.vala"
static void rygel_content_directory_get_sort_capabilities_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action) {
#line 270 "rygel-content-directory.vala"
	g_return_if_fail (self != NULL);
#line 270 "rygel-content-directory.vala"
	g_return_if_fail (content_dir != NULL);
#line 270 "rygel-content-directory.vala"
	g_return_if_fail (action != NULL);
#line 273 "rygel-content-directory.vala"
	gupnp_service_action_set (action, "SortCaps", G_TYPE_STRING, RYGEL_MEDIA_OBJECTS_SORT_CAPS, NULL);
#line 275 "rygel-content-directory.vala"
	gupnp_service_action_return (action);
#line 963 "rygel-content-directory.c"
}


#line 279 "rygel-content-directory.vala"
static void rygel_content_directory_query_sort_capabilities (RygelContentDirectory* self, GUPnPService* content_dir, const char* variable, GValue* value) {
#line 279 "rygel-content-directory.vala"
	g_return_if_fail (self != NULL);
#line 279 "rygel-content-directory.vala"
	g_return_if_fail (content_dir != NULL);
#line 279 "rygel-content-directory.vala"
	g_return_if_fail (variable != NULL);
#line 283 "rygel-content-directory.vala"
	g_value_init (value, G_TYPE_STRING);
#line 284 "rygel-content-directory.vala"
	g_value_set_string (value, RYGEL_MEDIA_OBJECTS_SORT_CAPS);
#line 979 "rygel-content-directory.c"
}


#line 288 "rygel-content-directory.vala"
static void rygel_content_directory_get_feature_list_cb (RygelContentDirectory* self, GUPnPService* content_dir, GUPnPServiceAction* action) {
#line 288 "rygel-content-directory.vala"
	g_return_if_fail (self != NULL);
#line 288 "rygel-content-directory.vala"
	g_return_if_fail (content_dir != NULL);
#line 288 "rygel-content-directory.vala"
	g_return_if_fail (action != NULL);
#line 291 "rygel-content-directory.vala"
	gupnp_service_action_set (action, "FeatureList", G_TYPE_STRING, self->feature_list, NULL);
#line 293 "rygel-content-directory.vala"
	gupnp_service_action_return (action);
#line 995 "rygel-content-directory.c"
}


#line 297 "rygel-content-directory.vala"
static void rygel_content_directory_query_feature_list (RygelContentDirectory* self, GUPnPService* content_dir, const char* variable, GValue* value) {
#line 297 "rygel-content-directory.vala"
	g_return_if_fail (self != NULL);
#line 297 "rygel-content-directory.vala"
	g_return_if_fail (content_dir != NULL);
#line 297 "rygel-content-directory.vala"
	g_return_if_fail (variable != NULL);
#line 301 "rygel-content-directory.vala"
	g_value_init (value, G_TYPE_STRING);
#line 302 "rygel-content-directory.vala"
	g_value_set_string (value, self->feature_list);
#line 1011 "rygel-content-directory.c"
}


#line 305 "rygel-content-directory.vala"
static char* rygel_content_directory_create_container_update_ids (RygelContentDirectory* self) {
#line 1017 "rygel-content-directory.c"
	char* result = NULL;
	char* update_ids;
#line 305 "rygel-content-directory.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 306 "rygel-content-directory.vala"
	update_ids = g_strdup ("");
#line 1024 "rygel-content-directory.c"
	{
		GeeIterator* _container_it;
#line 308 "rygel-content-directory.vala"
		_container_it = gee_abstract_collection_iterator ((GeeAbstractCollection*) self->priv->updated_containers);
#line 308 "rygel-content-directory.vala"
		while (TRUE) {
#line 1031 "rygel-content-directory.c"
			RygelMediaContainer* container;
			char* _tmp4_;
			char* _tmp3_;
			char* _tmp2_;
			char* _tmp1_;
#line 308 "rygel-content-directory.vala"
			if (!gee_iterator_next (_container_it)) {
#line 308 "rygel-content-directory.vala"
				break;
#line 1041 "rygel-content-directory.c"
			}
#line 308 "rygel-content-directory.vala"
			container = (RygelMediaContainer*) gee_iterator_get (_container_it);
#line 309 "rygel-content-directory.vala"
			if (_vala_strcmp0 (update_ids, "") != 0) {
#line 1047 "rygel-content-directory.c"
				char* _tmp0_;
#line 310 "rygel-content-directory.vala"
				update_ids = (_tmp0_ = g_strconcat (update_ids, ",", NULL), _g_free0 (update_ids), _tmp0_);
#line 1051 "rygel-content-directory.c"
			}
#line 313 "rygel-content-directory.vala"
			update_ids = (_tmp4_ = g_strconcat (update_ids, _tmp3_ = g_strconcat (_tmp1_ = g_strconcat (((RygelMediaObject*) container)->id, ",", NULL), _tmp2_ = g_strdup_printf ("%u", container->update_id), NULL), NULL), _g_free0 (update_ids), _tmp4_);
#line 1055 "rygel-content-directory.c"
			_g_free0 (_tmp3_);
			_g_free0 (_tmp2_);
			_g_free0 (_tmp1_);
			_g_object_unref0 (container);
		}
		_g_object_unref0 (_container_it);
	}
	result = update_ids;
#line 316 "rygel-content-directory.vala"
	return result;
#line 1066 "rygel-content-directory.c"
}


#line 348 "rygel-content-directory.vala"
static gboolean _rygel_content_directory_update_notify_gsource_func (gpointer self) {
#line 1072 "rygel-content-directory.c"
	gboolean result;
	result = rygel_content_directory_update_notify (self);
	return result;
}


#line 330 "rygel-content-directory.vala"
static void rygel_content_directory_on_container_updated (RygelContentDirectory* self, RygelMediaContainer* root_container, RygelMediaContainer* updated_container) {
#line 330 "rygel-content-directory.vala"
	g_return_if_fail (self != NULL);
#line 330 "rygel-content-directory.vala"
	g_return_if_fail (root_container != NULL);
#line 330 "rygel-content-directory.vala"
	g_return_if_fail (updated_container != NULL);
#line 332 "rygel-content-directory.vala"
	self->system_update_id++;
#line 334 "rygel-content-directory.vala"
	if (self->priv->clear_updated_containers) {
#line 335 "rygel-content-directory.vala"
		gee_abstract_collection_clear ((GeeAbstractCollection*) self->priv->updated_containers);
#line 336 "rygel-content-directory.vala"
		self->priv->clear_updated_containers = FALSE;
#line 1095 "rygel-content-directory.c"
	}
#line 340 "rygel-content-directory.vala"
	gee_abstract_collection_remove ((GeeAbstractCollection*) self->priv->updated_containers, updated_container);
#line 341 "rygel-content-directory.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) self->priv->updated_containers, updated_container);
#line 343 "rygel-content-directory.vala"
	if (self->priv->update_notify_id == 0) {
#line 344 "rygel-content-directory.vala"
		self->priv->update_notify_id = g_timeout_add_full (G_PRIORITY_DEFAULT, (guint) 200, _rygel_content_directory_update_notify_gsource_func, g_object_ref (self), g_object_unref);
#line 1105 "rygel-content-directory.c"
	}
}


#line 348 "rygel-content-directory.vala"
static gboolean rygel_content_directory_update_notify (RygelContentDirectory* self) {
#line 1112 "rygel-content-directory.c"
	gboolean result = FALSE;
	char* update_ids;
#line 348 "rygel-content-directory.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 349 "rygel-content-directory.vala"
	update_ids = rygel_content_directory_create_container_update_ids (self);
#line 351 "rygel-content-directory.vala"
	gupnp_service_notify ((GUPnPService*) self, "ContainerUpdateIDs", G_TYPE_STRING, update_ids, NULL);
#line 352 "rygel-content-directory.vala"
	gupnp_service_notify ((GUPnPService*) self, "SystemUpdateID", G_TYPE_UINT, self->system_update_id, NULL);
#line 354 "rygel-content-directory.vala"
	self->priv->clear_updated_containers = TRUE;
#line 355 "rygel-content-directory.vala"
	self->priv->update_notify_id = (guint) 0;
#line 1127 "rygel-content-directory.c"
	result = FALSE;
	_g_free0 (update_ids);
#line 357 "rygel-content-directory.vala"
	return result;
#line 1132 "rygel-content-directory.c"
}


#line 360 "rygel-content-directory.vala"
static char* rygel_content_directory_create_transfer_ids (RygelContentDirectory* self) {
#line 1138 "rygel-content-directory.c"
	char* result = NULL;
	char* ids;
#line 360 "rygel-content-directory.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 361 "rygel-content-directory.vala"
	ids = g_strdup ("");
#line 1145 "rygel-content-directory.c"
	{
		GeeIterator* _import_it;
#line 363 "rygel-content-directory.vala"
		_import_it = gee_abstract_collection_iterator ((GeeAbstractCollection*) self->priv->active_imports);
#line 363 "rygel-content-directory.vala"
		while (TRUE) {
#line 1152 "rygel-content-directory.c"
			RygelImportResource* import;
#line 363 "rygel-content-directory.vala"
			if (!gee_iterator_next (_import_it)) {
#line 363 "rygel-content-directory.vala"
				break;
#line 1158 "rygel-content-directory.c"
			}
#line 363 "rygel-content-directory.vala"
			import = (RygelImportResource*) gee_iterator_get (_import_it);
#line 364 "rygel-content-directory.vala"
			if (import->status != RYGEL_TRANSFER_STATUS_COMPLETED) {
#line 1164 "rygel-content-directory.c"
				char* _tmp2_;
				char* _tmp1_;
#line 365 "rygel-content-directory.vala"
				if (_vala_strcmp0 (ids, "") != 0) {
#line 1169 "rygel-content-directory.c"
					char* _tmp0_;
#line 366 "rygel-content-directory.vala"
					ids = (_tmp0_ = g_strconcat (ids, ",", NULL), _g_free0 (ids), _tmp0_);
#line 1173 "rygel-content-directory.c"
				}
#line 369 "rygel-content-directory.vala"
				ids = (_tmp2_ = g_strconcat (ids, _tmp1_ = g_strdup_printf ("%u", import->transfer_id), NULL), _g_free0 (ids), _tmp2_);
#line 1177 "rygel-content-directory.c"
				_g_free0 (_tmp1_);
			}
			_g_object_unref0 (import);
		}
		_g_object_unref0 (_import_it);
	}
	result = ids;
#line 373 "rygel-content-directory.vala"
	return result;
#line 1187 "rygel-content-directory.c"
}


#line 385 "rygel-content-directory.vala"
static gboolean _lambda8_ (Block1Data* _data1_) {
#line 1193 "rygel-content-directory.c"
	RygelContentDirectory * self;
	gboolean result = FALSE;
	self = _data1_->self;
#line 386 "rygel-content-directory.vala"
	gee_abstract_collection_remove ((GeeAbstractCollection*) self->priv->active_imports, _data1_->import);
#line 1199 "rygel-content-directory.c"
	result = FALSE;
#line 388 "rygel-content-directory.vala"
	return result;
#line 1203 "rygel-content-directory.c"
}


#line 385 "rygel-content-directory.vala"
static gboolean __lambda8__gsource_func (gpointer self) {
#line 1209 "rygel-content-directory.c"
	gboolean result;
	result = _lambda8_ (self);
	return result;
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}


static void block1_data_unref (Block1Data* _data1_) {
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		_g_object_unref0 (_data1_->self);
		_g_object_unref0 (_data1_->import);
		g_slice_free (Block1Data, _data1_);
	}
}


#line 376 "rygel-content-directory.vala"
static void rygel_content_directory_on_import_completed (RygelContentDirectory* self, RygelStateMachine* machine) {
#line 1233 "rygel-content-directory.c"
	Block1Data* _data1_;
	RygelStateMachine* _tmp0_;
	char* _tmp1_;
#line 376 "rygel-content-directory.vala"
	g_return_if_fail (self != NULL);
#line 376 "rygel-content-directory.vala"
	g_return_if_fail (machine != NULL);
#line 1241 "rygel-content-directory.c"
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	_data1_->self = g_object_ref (self);
	_data1_->import = _g_object_ref0 ((_tmp0_ = machine, RYGEL_IS_IMPORT_RESOURCE (_tmp0_) ? ((RygelImportResource*) _tmp0_) : NULL));
#line 379 "rygel-content-directory.vala"
	gupnp_service_notify ((GUPnPService*) self, "TransferIDs", G_TYPE_STRING, _tmp1_ = rygel_content_directory_create_transfer_ids (self), NULL);
#line 1248 "rygel-content-directory.c"
	_g_free0 (_tmp1_);
#line 385 "rygel-content-directory.vala"
	g_timeout_add_seconds_full (G_PRIORITY_DEFAULT, (guint) 30, __lambda8__gsource_func, block1_data_ref (_data1_), block1_data_unref);
#line 1252 "rygel-content-directory.c"
	block1_data_unref (_data1_);
}


#line 392 "rygel-content-directory.vala"
static RygelImportResource* rygel_content_directory_find_import_for_action (RygelContentDirectory* self, GUPnPServiceAction* action) {
#line 1259 "rygel-content-directory.c"
	RygelImportResource* result = NULL;
	RygelImportResource* ret;
	guint32 transfer_id = 0U;
#line 392 "rygel-content-directory.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 392 "rygel-content-directory.vala"
	g_return_val_if_fail (action != NULL, NULL);
#line 393 "rygel-content-directory.vala"
	ret = NULL;
#line 396 "rygel-content-directory.vala"
	gupnp_service_action_get (action, "TransferID", G_TYPE_UINT, &transfer_id, NULL);
#line 1271 "rygel-content-directory.c"
	{
		GeeIterator* _import_it;
#line 400 "rygel-content-directory.vala"
		_import_it = gee_abstract_collection_iterator ((GeeAbstractCollection*) self->priv->active_imports);
#line 400 "rygel-content-directory.vala"
		while (TRUE) {
#line 1278 "rygel-content-directory.c"
			RygelImportResource* import;
#line 400 "rygel-content-directory.vala"
			if (!gee_iterator_next (_import_it)) {
#line 400 "rygel-content-directory.vala"
				break;
#line 1284 "rygel-content-directory.c"
			}
#line 400 "rygel-content-directory.vala"
			import = (RygelImportResource*) gee_iterator_get (_import_it);
#line 401 "rygel-content-directory.vala"
			if (import->transfer_id == transfer_id) {
#line 1290 "rygel-content-directory.c"
				RygelImportResource* _tmp0_;
#line 402 "rygel-content-directory.vala"
				ret = (_tmp0_ = _g_object_ref0 (import), _g_object_unref0 (ret), _tmp0_);
#line 1294 "rygel-content-directory.c"
				_g_object_unref0 (import);
#line 404 "rygel-content-directory.vala"
				break;
#line 1298 "rygel-content-directory.c"
			}
			_g_object_unref0 (import);
		}
		_g_object_unref0 (_import_it);
	}
	result = ret;
#line 408 "rygel-content-directory.vala"
	return result;
#line 1307 "rygel-content-directory.c"
}


#line 44 "rygel-content-directory.vala"
RygelContentDirectory* rygel_content_directory_construct (GType object_type) {
#line 1313 "rygel-content-directory.c"
	RygelContentDirectory * self;
	self = g_object_newv (object_type, 0, NULL);
	return self;
}


#line 44 "rygel-content-directory.vala"
RygelContentDirectory* rygel_content_directory_new (void) {
#line 44 "rygel-content-directory.vala"
	return rygel_content_directory_construct (RYGEL_TYPE_CONTENT_DIRECTORY);
#line 1324 "rygel-content-directory.c"
}


static void rygel_content_directory_class_init (RygelContentDirectoryClass * klass) {
	rygel_content_directory_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (RygelContentDirectoryPrivate));
	G_OBJECT_CLASS (klass)->constructed = rygel_content_directory_real_constructed;
	G_OBJECT_CLASS (klass)->finalize = rygel_content_directory_finalize;
}


static void rygel_content_directory_instance_init (RygelContentDirectory * self) {
	self->priv = RYGEL_CONTENT_DIRECTORY_GET_PRIVATE (self);
}


static void rygel_content_directory_finalize (GObject* obj) {
	RygelContentDirectory * self;
	self = RYGEL_CONTENT_DIRECTORY (obj);
	{
#line 138 "rygel-content-directory.vala"
		g_cancellable_cancel (self->cancellable);
#line 1347 "rygel-content-directory.c"
	}
	_g_free0 (self->feature_list);
	_g_object_unref0 (self->http_server);
	_g_object_unref0 (self->root_container);
	_g_object_unref0 (self->priv->updated_containers);
	_g_object_unref0 (self->priv->active_imports);
	_g_object_unref0 (self->cancellable);
	G_OBJECT_CLASS (rygel_content_directory_parent_class)->finalize (obj);
}


GType rygel_content_directory_get_type (void) {
	static volatile gsize rygel_content_directory_type_id__volatile = 0;
	if (g_once_init_enter (&rygel_content_directory_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (RygelContentDirectoryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) rygel_content_directory_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RygelContentDirectory), 0, (GInstanceInitFunc) rygel_content_directory_instance_init, NULL };
		GType rygel_content_directory_type_id;
		rygel_content_directory_type_id = g_type_register_static (GUPNP_TYPE_SERVICE, "RygelContentDirectory", &g_define_type_info, 0);
		g_once_init_leave (&rygel_content_directory_type_id__volatile, rygel_content_directory_type_id);
	}
	return rygel_content_directory_type_id__volatile;
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




