/* rygel-tracker-video-item-factory.c generated by valac, the Vala compiler
 * generated from rygel-tracker-video-item-factory.vala, do not modify */

/*
 * Copyright (C) 2008 Zeeshan Ali <zeenix@gmail.com>.
 * Copyright (C) 2008 Nokia Corporation.
 *
 * Author: Zeeshan Ali <zeenix@gmail.com>
 *
 * This file is part of Rygel.
 *
 * Rygel is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Rygel is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <rygel.h>
#include <gee.h>


#define RYGEL_TYPE_TRACKER_ITEM_FACTORY (rygel_tracker_item_factory_get_type ())
#define RYGEL_TRACKER_ITEM_FACTORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_TRACKER_ITEM_FACTORY, RygelTrackerItemFactory))
#define RYGEL_TRACKER_ITEM_FACTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_TRACKER_ITEM_FACTORY, RygelTrackerItemFactoryClass))
#define RYGEL_IS_TRACKER_ITEM_FACTORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_TRACKER_ITEM_FACTORY))
#define RYGEL_IS_TRACKER_ITEM_FACTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_TRACKER_ITEM_FACTORY))
#define RYGEL_TRACKER_ITEM_FACTORY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_TRACKER_ITEM_FACTORY, RygelTrackerItemFactoryClass))

typedef struct _RygelTrackerItemFactory RygelTrackerItemFactory;
typedef struct _RygelTrackerItemFactoryClass RygelTrackerItemFactoryClass;
typedef struct _RygelTrackerItemFactoryPrivate RygelTrackerItemFactoryPrivate;

#define RYGEL_TYPE_TRACKER_SEARCH_CONTAINER (rygel_tracker_search_container_get_type ())
#define RYGEL_TRACKER_SEARCH_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_TRACKER_SEARCH_CONTAINER, RygelTrackerSearchContainer))
#define RYGEL_TRACKER_SEARCH_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_TRACKER_SEARCH_CONTAINER, RygelTrackerSearchContainerClass))
#define RYGEL_IS_TRACKER_SEARCH_CONTAINER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_TRACKER_SEARCH_CONTAINER))
#define RYGEL_IS_TRACKER_SEARCH_CONTAINER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_TRACKER_SEARCH_CONTAINER))
#define RYGEL_TRACKER_SEARCH_CONTAINER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_TRACKER_SEARCH_CONTAINER, RygelTrackerSearchContainerClass))

typedef struct _RygelTrackerSearchContainer RygelTrackerSearchContainer;
typedef struct _RygelTrackerSearchContainerClass RygelTrackerSearchContainerClass;

#define RYGEL_TYPE_TRACKER_VIDEO_ITEM_FACTORY (rygel_tracker_video_item_factory_get_type ())
#define RYGEL_TRACKER_VIDEO_ITEM_FACTORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), RYGEL_TYPE_TRACKER_VIDEO_ITEM_FACTORY, RygelTrackerVideoItemFactory))
#define RYGEL_TRACKER_VIDEO_ITEM_FACTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), RYGEL_TYPE_TRACKER_VIDEO_ITEM_FACTORY, RygelTrackerVideoItemFactoryClass))
#define RYGEL_IS_TRACKER_VIDEO_ITEM_FACTORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), RYGEL_TYPE_TRACKER_VIDEO_ITEM_FACTORY))
#define RYGEL_IS_TRACKER_VIDEO_ITEM_FACTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), RYGEL_TYPE_TRACKER_VIDEO_ITEM_FACTORY))
#define RYGEL_TRACKER_VIDEO_ITEM_FACTORY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), RYGEL_TYPE_TRACKER_VIDEO_ITEM_FACTORY, RygelTrackerVideoItemFactoryClass))

typedef struct _RygelTrackerVideoItemFactory RygelTrackerVideoItemFactory;
typedef struct _RygelTrackerVideoItemFactoryClass RygelTrackerVideoItemFactoryClass;
typedef struct _RygelTrackerVideoItemFactoryPrivate RygelTrackerVideoItemFactoryPrivate;

#define RYGEL_TRACKER_ITEM_FACTORY_TYPE_METADATA (rygel_tracker_item_factory_metadata_get_type ())

#define RYGEL_TRACKER_VIDEO_ITEM_FACTORY_TYPE_VIDEO_METADATA (rygel_tracker_video_item_factory_video_metadata_get_type ())
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _RygelTrackerItemFactory {
	GTypeInstance parent_instance;
	volatile int ref_count;
	RygelTrackerItemFactoryPrivate * priv;
	char* category;
	char* upnp_class;
	char* resources_class_path;
	char* upload_dir;
	GeeArrayList* key_chains;
};

struct _RygelTrackerItemFactoryClass {
	GTypeClass parent_class;
	void (*finalize) (RygelTrackerItemFactory *self);
	RygelMediaItem* (*create) (RygelTrackerItemFactory* self, const char* id, const char* uri, RygelTrackerSearchContainer* parent, char** metadata, int metadata_length1, GError** error);
};

struct _RygelTrackerVideoItemFactory {
	RygelTrackerItemFactory parent_instance;
	RygelTrackerVideoItemFactoryPrivate * priv;
};

struct _RygelTrackerVideoItemFactoryClass {
	RygelTrackerItemFactoryClass parent_class;
};

typedef enum  {
	RYGEL_TRACKER_ITEM_FACTORY_METADATA_FILE_NAME,
	RYGEL_TRACKER_ITEM_FACTORY_METADATA_TITLE,
	RYGEL_TRACKER_ITEM_FACTORY_METADATA_MIME,
	RYGEL_TRACKER_ITEM_FACTORY_METADATA_SIZE,
	RYGEL_TRACKER_ITEM_FACTORY_METADATA_DATE,
	RYGEL_TRACKER_ITEM_FACTORY_METADATA_LAST_KEY
} RygelTrackerItemFactoryMetadata;

typedef enum  {
	RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_HEIGHT = RYGEL_TRACKER_ITEM_FACTORY_METADATA_LAST_KEY,
	RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_WIDTH,
	RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_DURATION,
	RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_LAST_KEY
} RygelTrackerVideoItemFactoryVideoMetadata;


static gpointer rygel_tracker_video_item_factory_parent_class = NULL;

gpointer rygel_tracker_item_factory_ref (gpointer instance);
void rygel_tracker_item_factory_unref (gpointer instance);
GParamSpec* rygel_param_spec_tracker_item_factory (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void rygel_value_set_tracker_item_factory (GValue* value, gpointer v_object);
void rygel_value_take_tracker_item_factory (GValue* value, gpointer v_object);
gpointer rygel_value_get_tracker_item_factory (const GValue* value);
GType rygel_tracker_item_factory_get_type (void);
GType rygel_tracker_search_container_get_type (void);
GType rygel_tracker_video_item_factory_get_type (void);
enum  {
	RYGEL_TRACKER_VIDEO_ITEM_FACTORY_DUMMY_PROPERTY
};
GType rygel_tracker_item_factory_metadata_get_type (void);
static GType rygel_tracker_video_item_factory_video_metadata_get_type (void) G_GNUC_UNUSED;
#define RYGEL_TRACKER_VIDEO_ITEM_FACTORY_CATEGORY "nmm:Video"
#define RYGEL_RESOURCES_CLASS_PATH "/org/freedesktop/Tracker1/" "Resources/Classes/"
#define RYGEL_VIDEO_RESOURCES_CLASS_PATH RYGEL_RESOURCES_CLASS_PATH "nmm/Video"
RygelTrackerItemFactory* rygel_tracker_item_factory_construct (GType object_type, const char* category, const char* upnp_class, const char* resources_class_path, const char* upload_dir);
RygelTrackerVideoItemFactory* rygel_tracker_video_item_factory_new (void);
RygelTrackerVideoItemFactory* rygel_tracker_video_item_factory_construct (GType object_type);
RygelMediaItem* rygel_tracker_item_factory_create (RygelTrackerItemFactory* self, const char* id, const char* uri, RygelTrackerSearchContainer* parent, char** metadata, int metadata_length1, GError** error);
static RygelMediaItem* rygel_tracker_video_item_factory_real_create (RygelTrackerItemFactory* base, const char* id, const char* uri, RygelTrackerSearchContainer* parent, char** metadata, int metadata_length1, GError** error);
static int _vala_strcmp0 (const char * str1, const char * str2);



static GType rygel_tracker_video_item_factory_video_metadata_get_type (void) {
	static volatile gsize rygel_tracker_video_item_factory_video_metadata_type_id__volatile = 0;
	if (g_once_init_enter (&rygel_tracker_video_item_factory_video_metadata_type_id__volatile)) {
		static const GEnumValue values[] = {{RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_HEIGHT, "RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_HEIGHT", "height"}, {RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_WIDTH, "RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_WIDTH", "width"}, {RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_DURATION, "RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_DURATION", "duration"}, {RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_LAST_KEY, "RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_LAST_KEY", "last-key"}, {0, NULL, NULL}};
		GType rygel_tracker_video_item_factory_video_metadata_type_id;
		rygel_tracker_video_item_factory_video_metadata_type_id = g_enum_register_static ("RygelTrackerVideoItemFactoryVideoMetadata", values);
		g_once_init_leave (&rygel_tracker_video_item_factory_video_metadata_type_id__volatile, rygel_tracker_video_item_factory_video_metadata_type_id);
	}
	return rygel_tracker_video_item_factory_video_metadata_type_id__volatile;
}


#line 40 "rygel-tracker-video-item-factory.vala"
RygelTrackerVideoItemFactory* rygel_tracker_video_item_factory_construct (GType object_type) {
#line 158 "rygel-tracker-video-item-factory.c"
	RygelTrackerVideoItemFactory* self;
	GeeArrayList* _tmp2_;
	GeeArrayList* _tmp3_;
	GeeArrayList* _tmp4_;
#line 41 "rygel-tracker-video-item-factory.vala"
	self = (RygelTrackerVideoItemFactory*) rygel_tracker_item_factory_construct (object_type, RYGEL_TRACKER_VIDEO_ITEM_FACTORY_CATEGORY, RYGEL_MEDIA_ITEM_VIDEO_CLASS, RYGEL_VIDEO_RESOURCES_CLASS_PATH, g_get_user_special_dir (G_USER_DIRECTORY_VIDEOS));
#line 165 "rygel-tracker-video-item-factory.c"
	{
		gint i;
#line 46 "rygel-tracker-video-item-factory.vala"
		i = gee_collection_get_size ((GeeCollection*) ((RygelTrackerItemFactory*) self)->key_chains);
#line 170 "rygel-tracker-video-item-factory.c"
		{
			gboolean _tmp0_;
#line 46 "rygel-tracker-video-item-factory.vala"
			_tmp0_ = TRUE;
#line 46 "rygel-tracker-video-item-factory.vala"
			while (TRUE) {
#line 177 "rygel-tracker-video-item-factory.c"
				GeeArrayList* _tmp1_;
#line 46 "rygel-tracker-video-item-factory.vala"
				if (!_tmp0_) {
#line 46 "rygel-tracker-video-item-factory.vala"
					i++;
#line 183 "rygel-tracker-video-item-factory.c"
				}
#line 46 "rygel-tracker-video-item-factory.vala"
				_tmp0_ = FALSE;
#line 46 "rygel-tracker-video-item-factory.vala"
				if (!(i < RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_LAST_KEY)) {
#line 46 "rygel-tracker-video-item-factory.vala"
					break;
#line 191 "rygel-tracker-video-item-factory.c"
				}
#line 47 "rygel-tracker-video-item-factory.vala"
				gee_abstract_collection_add ((GeeAbstractCollection*) ((RygelTrackerItemFactory*) self)->key_chains, _tmp1_ = gee_array_list_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, NULL));
#line 195 "rygel-tracker-video-item-factory.c"
				_g_object_unref0 (_tmp1_);
			}
		}
	}
#line 50 "rygel-tracker-video-item-factory.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) (_tmp2_ = (GeeArrayList*) gee_abstract_list_get ((GeeAbstractList*) ((RygelTrackerItemFactory*) self)->key_chains, (gint) RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_WIDTH)), "nfo:width");
#line 202 "rygel-tracker-video-item-factory.c"
	_g_object_unref0 (_tmp2_);
#line 51 "rygel-tracker-video-item-factory.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) (_tmp3_ = (GeeArrayList*) gee_abstract_list_get ((GeeAbstractList*) ((RygelTrackerItemFactory*) self)->key_chains, (gint) RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_HEIGHT)), "nfo:height");
#line 206 "rygel-tracker-video-item-factory.c"
	_g_object_unref0 (_tmp3_);
#line 52 "rygel-tracker-video-item-factory.vala"
	gee_abstract_collection_add ((GeeAbstractCollection*) (_tmp4_ = (GeeArrayList*) gee_abstract_list_get ((GeeAbstractList*) ((RygelTrackerItemFactory*) self)->key_chains, (gint) RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_DURATION)), "nfo:duration");
#line 210 "rygel-tracker-video-item-factory.c"
	_g_object_unref0 (_tmp4_);
	return self;
}


#line 40 "rygel-tracker-video-item-factory.vala"
RygelTrackerVideoItemFactory* rygel_tracker_video_item_factory_new (void) {
#line 40 "rygel-tracker-video-item-factory.vala"
	return rygel_tracker_video_item_factory_construct (RYGEL_TYPE_TRACKER_VIDEO_ITEM_FACTORY);
#line 220 "rygel-tracker-video-item-factory.c"
}


#line 55 "rygel-tracker-video-item-factory.vala"
static RygelMediaItem* rygel_tracker_video_item_factory_real_create (RygelTrackerItemFactory* base, const char* id, const char* uri, RygelTrackerSearchContainer* parent, char** metadata, int metadata_length1, GError** error) {
#line 226 "rygel-tracker-video-item-factory.c"
	RygelTrackerVideoItemFactory * self;
	RygelMediaItem* result = NULL;
	GError * _inner_error_;
	RygelMediaItem* item;
	self = (RygelTrackerVideoItemFactory*) base;
#line 55 "rygel-tracker-video-item-factory.vala"
	g_return_val_if_fail (id != NULL, NULL);
#line 55 "rygel-tracker-video-item-factory.vala"
	g_return_val_if_fail (uri != NULL, NULL);
#line 55 "rygel-tracker-video-item-factory.vala"
	g_return_val_if_fail (parent != NULL, NULL);
#line 238 "rygel-tracker-video-item-factory.c"
	_inner_error_ = NULL;
#line 60 "rygel-tracker-video-item-factory.vala"
	item = RYGEL_TRACKER_ITEM_FACTORY_CLASS (rygel_tracker_video_item_factory_parent_class)->create (RYGEL_TRACKER_ITEM_FACTORY (self), id, uri, parent, metadata, metadata_length1, &_inner_error_);
#line 242 "rygel-tracker-video-item-factory.c"
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return NULL;
	}
#line 62 "rygel-tracker-video-item-factory.vala"
	if (_vala_strcmp0 (metadata[RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_WIDTH], "") != 0) {
#line 63 "rygel-tracker-video-item-factory.vala"
		item->width = atoi (metadata[RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_WIDTH]);
#line 251 "rygel-tracker-video-item-factory.c"
	}
#line 65 "rygel-tracker-video-item-factory.vala"
	if (_vala_strcmp0 (metadata[RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_HEIGHT], "") != 0) {
#line 66 "rygel-tracker-video-item-factory.vala"
		item->height = atoi (metadata[RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_HEIGHT]);
#line 257 "rygel-tracker-video-item-factory.c"
	}
#line 68 "rygel-tracker-video-item-factory.vala"
	if (_vala_strcmp0 (metadata[RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_DURATION], "") != 0) {
#line 69 "rygel-tracker-video-item-factory.vala"
		item->duration = (glong) atoi (metadata[RYGEL_TRACKER_VIDEO_ITEM_FACTORY_VIDEO_METADATA_DURATION]);
#line 263 "rygel-tracker-video-item-factory.c"
	}
	result = item;
#line 71 "rygel-tracker-video-item-factory.vala"
	return result;
#line 268 "rygel-tracker-video-item-factory.c"
}


static void rygel_tracker_video_item_factory_class_init (RygelTrackerVideoItemFactoryClass * klass) {
	rygel_tracker_video_item_factory_parent_class = g_type_class_peek_parent (klass);
	RYGEL_TRACKER_ITEM_FACTORY_CLASS (klass)->create = rygel_tracker_video_item_factory_real_create;
}


static void rygel_tracker_video_item_factory_instance_init (RygelTrackerVideoItemFactory * self) {
}


GType rygel_tracker_video_item_factory_get_type (void) {
	static volatile gsize rygel_tracker_video_item_factory_type_id__volatile = 0;
	if (g_once_init_enter (&rygel_tracker_video_item_factory_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (RygelTrackerVideoItemFactoryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) rygel_tracker_video_item_factory_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (RygelTrackerVideoItemFactory), 0, (GInstanceInitFunc) rygel_tracker_video_item_factory_instance_init, NULL };
		GType rygel_tracker_video_item_factory_type_id;
		rygel_tracker_video_item_factory_type_id = g_type_register_static (RYGEL_TYPE_TRACKER_ITEM_FACTORY, "RygelTrackerVideoItemFactory", &g_define_type_info, 0);
		g_once_init_leave (&rygel_tracker_video_item_factory_type_id__volatile, rygel_tracker_video_item_factory_type_id);
	}
	return rygel_tracker_video_item_factory_type_id__volatile;
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




